### PR TITLE
Update help docs

### PR DESCRIPTION
**Pull request by Priyatham10**

### CODE REVIEW

**Comment by pyscripter** [comment]
Thanks very much for updating the help files.
Just one request before I merge.   Can we restrict this PR to the help files?   The change in Readme.md could be part of a separate PR,

**Comment by Priyatham10** [comment]
Yes, Sure Kiriakos. We can add READM.md to another PR. That change was performed by @jimmckeeth when forking it into our working environment. I think we still have a lot of changes to make. It was only the first 3 section help doc files in this recent commit.  Let's currently keep the PR open. I will make more updates to other help files and push them.

**Comment by pyscripter** [comment]
Good.  Regarding the help files, I want to bring to your attention #1164 which I thought at the time it was a good idea.   However there was no follow up.

**Comment by Priyatham10** [comment]
Yes, I too got a similar idea as I'm working on it where I thought it would be good to choose markdown. But I didn't have a nice experience serving the markdown viewer into the PyScripter using Delphi, so I dropped that plan. I thought of discussing that idea with @jimmckeeth and Lucas Belo to implement that. But, until then, I didn't stop as we can always convert the HTML to markdown at any time. The Restructured text also is good, but we can have more community outreach as far as help file updates in future because markdown is known to more people compared to restructured text.

**Comment by Priyatham10** [comment]
@pyscripter I've written a book on Programming with Python. Have a plan to write advanced Python programming in the near future. It needs more edits and polishing. It's currently under review by @jimmckeeth . I thought we could provide a link to that eBook for the `Python Manuals` button in the help submenu. What do you think of this idea?

**Comment by pyscripter** [comment]
Yes sure!

**Comment by Priyatham10** [comment]
Hi Kiriakos,

You can merge this PR. I will update the remaining help docs again as Lucas implements the Android development features.

**Pull request merged**
