### PR TITLE
Icons are splited as individual svg file

### PR DESCRIPTION
**Pull request by sk-Prime**
default dimension of each icon is 32x32, except gutter those are 14x11 (i kept original icon dimension)

### CODE REVIEW

**Comment by pyscripter** [comment]
Great thanks!!!!

**Comment by sk-Prime** [comment]
Welcome. What do you think about dynamically changing icon color. For example if we flatten each icon to one shape with solid color, you can simply change svg tag to change its color.
look at browser2.svg file
browser normal
after flatten it looks like this
modern browser 2
Though it looks flat(as flattened) but easy to handle. just changing `style="fill:#008000;` to `style="fill:#ff0000;` will give you red color icon. if you can change it programmatically like using rgb slider you will get the option to select whatever color you want to use. 
red

**Comment by pyscripter** [comment]
The svgs look great!!   There is small issue with two of them (tool74 and tool75 which are missing the second #).  I would greatful if you could fix them.  Also a small number of icons are using the text element.  The Windows Direct2D Svg does not support the text element.  Could you please use the ObjectToPath command of Inkscape to replace text with path?

Flat Icons will be most welcome and in line with material design.   You can add them in a new directory "flat" and keep the existing ones in "default"

Questions: 
- In your example above the arrow fill color is white (fill:white).   Should it be none instead so that it takes the background color?  
- In many icons we are using many colors.  Are you suggesting that we move to monochrome icons?

**Comment by sk-Prime** [comment]
i submitted new pull request with fixes  #1012 
##### optimization
opening each file in inkscape and saving them is time consuming, i would suggest https://github.com/RazrFalcon/svgcleaner-gui this tool, because it is a batch optimizer. just select `scalable` folder and choose output folder. i already tried it and it did decent job. For example tool106.svg becomes 1.8KB

i have already optimized all icons using this tools. I suggest you to give it a try and tell me if you are happy with the result. If you want me, i can make a new pull request with those optimized icons. 

##### answer
1. arrow fill color is not white. that is the background color. As i said "making one shape", arrow and circle are two shape. I cut some region of circle using the arrow so it becomes one shape.
2. Better to say one solid color. All icon will be same one solid color. otherwise it will be difficult to change color programmatically. 

let's say the background color is black, programmatically change all icon to be white.  just replace previous color with `#ffffff` and border maybe another color.

**Comment by pyscripter** [comment]
Already merged! Many thanks!

svgcleaner looks very impressing.  It has more [options](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc) than any other tool I found.   Please submit the optimized icons in PR.  Is there a point in keeping both the original and the optimized?  If  yes put them in a subdirectory of default say optimized_svgs.

Regarding the fill color I very much like your suggestion.  I will be using a [specialized ImageList](https://github.com/EtheaDev/SVGIconImageList) that makes it very easy to change the Fill color of all icons at run time.
Looking forward to looking at the results!!

**Pull request merged**
