### PR TITLE
fixed editor gutter dimension

### PR DESCRIPTION
**Pull request by sk-Prime**

### CODE REVIEW

**Comment by pyscripter** [comment]
The editor gutter dimensions are wrong in 24x24 and 32x32 directories as well as in the svg source.  Any chance of fixing that?

**Comment by sk-Prime** [comment]
let me know, what is the expected dimension?

**Comment by pyscripter** [comment]
The 24x24 directory should include rounded dimensions 21x16 and the 32x32 directory 28x22 (HxW).But never mind in my latest commit I tried to handle it myself.  I had to learn inkscape!  You may have a look to check whether what I have done is OK.

By the way I am now integrating the multiple resolution graphics into PyScripter and it looks great in high DPI.  THANK YOU VERY MUCH!!!

**Comment by pyscripter** [comment]
@sk-Prime   I hope you are doing well!
I am moving to a native SVG solution (no longer conversion to png) and I wonder about how to split the svg files you created into separate files for each icon.  Any suggestions?

**Comment by sk-Prime** [comment]
I am good, Thanks for asking. 

I can separate it no problem. If i make individual svg file for each icon what will be the name of each file.

**Comment by pyscripter** [comment]
Just call them Item0 Item1 etc. for now.  I will then rename them.

**Pull request merged**
