### PR TITLE
high defination logo for Pyscripter

### PR DESCRIPTION
**Pull request by sk-Prime**
i added three scalable vector graphics, which can be use to produce higher resolution raster image. i added raster image too, it is in png folder.

----
compare

first one is new version

### CODE REVIEW

**Comment by pyscripter** [comment]
@sk-Prime Thanks very much for the art-work.
I have moved your work into a folder called Art.  This folder contains a subfolder called Toolbars, which contains the images used in PyScripter Toolbars.  There is scope for improving these images.  Currently they come in 16x16 size.  In addition, I would appreciate help in producing 32x32 size versions of these images, that would improve the looks of PyScripter in high DPI monitors.
Help on this would be much appreciated.

Also the *.ico files in the PyScripter folder would benefit from the addition of higher resolution images.  Currently the largest size is 32x32 and adding 48x48 would be useful.

**Comment by sk-Prime** [comment]
welcome, i don't know pascal, but i have some experiences in graphics design. it is difficult for me to explore all the codes. so i will upload all graphics file in 'art' folder. you can pick them where you need.
so my todo list is
1. increasing the DPI of toolbars icon
2. producing 48x48 ico file

i have few plans, i will tell that after completing this.

**Comment by pyscripter** [comment]
Thanks very much.
There is no need to touch the code.  You can improve the icons inside the toolbar bpm files.  For example Toolbar_images_16x16.bmp contains something like 170 small glyphs each 16x16 bits.  You can replace those ones that are lower quality or do not feel well with the feel and look of pyscripter.  You can also produce a higher resolution version e.g. Toolbar_impages_32x32, which would contain the same icons but in a 32x32 resolution.  Even doing that for a subset of the original icons would be of help.

**Comment by sk-Prime** [comment]
is it mandatory to keep filetype as BMP. how about png, it has transparent background. bmp reduce quality of the image which affect 32x32 pixel image. take a look is it ok, if then i will work on other file

browser_32x32.png


i cant upload bmp here. bmp has magenta background as like original file.

**Comment by pyscripter** [comment]
Png is fine.

**Comment by pyscripter** [comment]
Wow.  This is fast.

**Comment by pyscripter** [comment]
Could you please provide an updated maching 16x16 image as well.

**Comment by sk-Prime** [comment]
sorry i can't get it, updated machine? (the printer?)

**Comment by pyscripter** [comment]
In this case they do much.   I thought you might  want to replace some pictures in other toolbars.  Images that have black color (for instance the select/deselect all in the main toolbar) do not show well on dark backgrounds.

One issue I have with the png files above is transparency.  The background does not appear to be transparent or at least Delphi does not recognize it as transparent.

**Comment by sk-Prime** [comment]
i will replace all pictures gradually. now i will test the pictures in different background to check how they appear.

Yes, the above png is transparent with RGBA color.
in bitmap (24 bit is RGB too, no alpha value in it) can you make it transparent? or delphi make them transparent. if 

oh sure, i added two pixels around each picture (128+2px*4picture)=136), i thought it make a nice gap between pictures. besides anti-aliasing sometime add extra pixel around the edge. so i will update "browser" picture list shortly. then inform me if everything is ok with that. so, i can work with other toolbar pictures accurately.

**Comment by pyscripter** [comment]
Excellent!
I could load the picture in Delphi after saving it as bitmap.  Delphi with bitmaps autodetects the transparent color but you can also specify it.   It is supposed to work also with png alpha transparency, but for some reason it din't.  However as I said this is not an issue.

**Comment by sk-Prime** [comment]
browser_16x16
browser_32x32
browser_64x64


take a look, and check if it is right, 16x16,32x32 and 64x64. i added inverse color outline to each picture so what ever the background color it will stand out.

**Comment by pyscripter** [comment]
Works perfectly.  Transparency is recognized by Delphi and there is no need to convert to bitmaps.

**Comment by pyscripter** [comment]
By the way, if you email at pyscripter at gmail.com  your name I will include it in the Credits (about box).  Otherwise I will include your GitHub user name.

**Comment by sk-Prime** [comment]
11-6-2018 3-41-28 pm

so far, i have completed first two lines of the big toolbar list. it is classic toolbar icon, i am trying to reproduce original icon as best as possible. maybe in future we can add modern icon in another folder. user can change as their demand.

**Pull request merged**
