### PR TITLE
fix icon horizontal line

### PR DESCRIPTION
**Pull request by sk-Prime**
11-15-2018 9-25-46 pm

there are some icons that have horizontal line at the top of it. it will fix the problem.

---------

i am glad about the new pyscripter release. Best wishes for pyscripter.

### CODE REVIEW

**Comment by pyscripter** [comment]
Fixed in 3.5.1

**Comment by pyscripter** [comment]
@sk-Prime In this PR you only changed Art/Icons/default/16x16/Toolbar_Images_16x16.png
You have not updated the source file and the other resolutions.  Unfortunately the lines still exist in the other resolutions.

Any change of updating the other resolutions and the source file?

PLEASE!!

**Comment by sk-Prime** [comment]
ok, i am testing it now.

**Comment by pyscripter** [comment]
Yes this is fine!  The 16x16 was also fine.

**Pull request merged**
